# Generated by Django 3.1.3 on 2021-01-04 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_confirmation_mail_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date confirmation mail sent'),
            preserve_default=False,
        ),
    ]
