# Generated by Django 3.1.3 on 2021-01-04 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_confirmation_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_confirmation_mail_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date confirmation mail sent'),
        ),
    ]
