# Generated by Django 3.1.3 on 2021-10-04 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_person', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_description', models.TextField()),
                ('rating', models.FloatField(choices=[(1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (4.0, 4.0), (5.0, 5.0)], max_length=3)),
                ('is_published', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, help_text='Provide an mobile number without +91', null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('is_booked', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_booked_offline', models.BooleanField(default=False)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('no_of_days', models.IntegerField(default=1)),
                ('ordered_date_time', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('payment_id', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('signature', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='room_type')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='rooms')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='rooms')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='rooms')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='rooms')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='rooms')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='rooms')),
                ('stock_no', models.IntegerField(blank=True, default=0, help_text='Qty of stock!', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('people_variation', models.ManyToManyField(blank=True, to='room.PeopleVariation')),
            ],
        ),
    ]
