# Generated by Django 3.1.3 on 2021-06-25 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='people_variation',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='price',
        ),
        migrations.RenameModel(
            old_name='Room',
            new_name='RoomBooked',
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='rooms')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('people_variation', models.ManyToManyField(blank=True, to='room.PeopleVariation')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomtype')),
            ],
        ),
        migrations.AlterField(
            model_name='roombooked',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.rooms'),
        ),
    ]
