# Generated by Django 3.1.3 on 2021-06-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210625_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
    ]
