# Generated by Django 3.1.2 on 2020-10-30 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='image_main',
            new_name='image',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='PlateItems',
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15, unique=True)),
                ('ordered_date', models.DateField()),
                ('ordered_time', models.TimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('total_items', models.IntegerField(blank=True, null=True)),
                ('items', models.ManyToManyField(to='home.PlateItems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
