# Generated by Django 3.1.3 on 2021-06-24 12:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tand_c', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipping_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('refund_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('return_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cancellation_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
