# Generated by Django 3.1.3 on 2021-01-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('Suggested', 'Suggested'), ('Special', 'Special'), ('Trending', 'Trending'), ('Top Selling', 'Top Selling'), ('Popular', 'Popular'), ('Chef selection', 'Chef selection')], help_text='Food Item is Special, Popular etc or leave it blank for no label.                                         (Label will be displayed over a item.)', max_length=14, null=True),
        ),
    ]
