# Generated by Django 3.1.3 on 2021-10-04 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
        ),
        migrations.AddField(
            model_name='booktable',
            name='people_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tablecount'),
        ),
        migrations.AddField(
            model_name='booktable',
            name='sitting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tableview'),
        ),
        migrations.AddField(
            model_name='booktable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.table'),
        ),
        migrations.AddField(
            model_name='booktable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
