# Generated by Django 3.1.3 on 2021-01-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210111_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
