# Generated by Django 3.1.3 on 2021-01-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210109_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_main',
            new_name='image',
        ),
    ]
