# Generated by Django 3.1.3 on 2021-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_booktable_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktable',
            options={'ordering': ['booked_for_date']},
        ),
        migrations.AddField(
            model_name='booktable',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
