# Generated by Django 3.1.3 on 2021-01-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_booktable_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='tablecount',
            name='title',
            field=models.IntegerField(unique=True),
        ),
    ]
