# Generated by Django 3.1.3 on 2021-01-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210109_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_per',
            field=models.CharField(blank=True, help_text='Cost of food item is per plate or per pcs', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50, null=True),
        ),
    ]
