# Generated by Django 3.1.3 on 2021-01-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210112_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_title',
        ),
    ]
