# Generated by Django 3.1.3 on 2021-01-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210110_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tablecount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tableview',
            name='is_active',
        ),
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=320)),
                ('phone_number', models.BigIntegerField()),
                ('booked_for_date', models.DateField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('booked_for_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tabletime')),
                ('people_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tablecount')),
                ('sitting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tableview')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.table')),
            ],
        ),
    ]
