# Generated by Django 3.1.3 on 2021-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20210201_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_class',
            field=models.BooleanField(default=False),
        ),
    ]
