# Generated by Django 3.1.3 on 2021-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_product_first_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='veg',
            field=models.BooleanField(default=True),
        ),
    ]
