# Generated by Django 3.1.3 on 2021-01-09 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0004_auto_20210109_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discount_percent', models.FloatField()),
                ('minimum_order_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('discount_amount', models.FloatField(null=True)),
                ('used', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('code', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MiniOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15)),
                ('mini_order_ref_number', models.CharField(default='MORN-100000', max_length=15, unique=True)),
                ('ordered_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordered', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Placed', 'Placed'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('CANCELED', 'CANCELED')], default='Preparing', max_length=50)),
                ('delivered_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_window', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_requested', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('payment_method', models.CharField(default='Online by card', max_length=30)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razor_pay_id', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_used', models.BooleanField(default=False)),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15, unique=True)),
                ('ordered_date_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('received', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_method', models.CharField(default='Online by card', max_length=30)),
                ('taxes', models.FloatField(default=0)),
                ('cart', models.ManyToManyField(to='order.Cart')),
                ('coupon_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.couponcustomer')),
                ('mini_order', models.ManyToManyField(to='order.MiniOrder')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_date_time'],
            },
        ),
        migrations.CreateModel(
            name='CancelMiniOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_requested', models.BooleanField(default=True)),
                ('cancel_status', models.CharField(choices=[('Processing Cancel Request', 'Processing Cancel Request'), ('CANCEL Denied', 'CANCEL Denied'), ('Cancel Granted', 'Cancel Granted')], default='Processing Cancel Request', max_length=50)),
                ('cancel_granted', models.BooleanField(default=False)),
                ('cancel_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancel_reason', models.CharField(blank=True, choices=[('Not Needed', 'Not Needed'), ('Ordered Wrong Product', 'Ordered Wrong Product'), ('Receiving To Late', 'Receiving To Late'), ('Select Different Payment Method', 'Select Different Payment Method'), ('Other', 'Other')], max_length=50, null=True)),
                ('review_description', models.TextField(help_text='Please Describe in detail reason of cancel.')),
                ('cancel_mini_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.miniorder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cancel_date'],
            },
        ),
    ]
