# Generated by Django 3.1.3 on 2021-10-04 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_requested', models.BooleanField(default=True)),
                ('cancel_status', models.CharField(choices=[('Processing Request', 'Processing Request'), ('CANCEL Denied', 'CANCEL Denied'), ('Cancel Granted', 'Cancel Granted')], default='Processing Cancel Request', max_length=50)),
                ('cancel_granted', models.BooleanField(default=False)),
                ('cancel_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancel_reason', models.CharField(blank=True, choices=[('Not Needed', 'Not Needed'), ('Ordered Wrong Dishes', 'Ordered Wrong Dishes'), ('Receiving To Late', 'Receiving To Late'), ('Other', 'Other')], max_length=50, null=True)),
                ('review_description', models.TextField(help_text='Please Describe in detail reason of cancel.')),
                ('is_seen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['cancel_date'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('CANCELED', 'CANCELED')], default='Processing', max_length=50)),
                ('order_ref_number', models.CharField(blank=True, max_length=15, null=True)),
                ('product_title', models.CharField(blank=True, max_length=200, null=True)),
                ('product_discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('variation_title', models.CharField(blank=True, max_length=200, null=True)),
                ('variation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('delivered_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discount_percent', models.FloatField()),
                ('minimum_order_amount', models.FloatField()),
                ('max_discount_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('discount_amount', models.FloatField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('session_user', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_user', models.CharField(blank=True, max_length=200, null=True)),
                ('coupon_used', models.BooleanField(default=False)),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15, unique=True)),
                ('ordered_date_time', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('CANCELED', 'CANCELED')], default='Processing', max_length=50)),
                ('seen', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-ordered_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_used', models.BooleanField(default=False)),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15, unique=True)),
                ('ordered_date_time', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('CANCELED', 'CANCELED')], default='Processing', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('received', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-ordered_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('payment_id', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('signature', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('session_user', models.CharField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('CANCELED', 'CANCELED')], default='Processing', max_length=50)),
                ('order_ref_number', models.CharField(blank=True, max_length=15, null=True)),
                ('product_title', models.CharField(blank=True, max_length=200, null=True)),
                ('product_discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('variation_title', models.CharField(blank=True, max_length=200, null=True)),
                ('variation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('delivered_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product')),
            ],
        ),
    ]
