# Generated by Django 3.1.3 on 2021-01-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mini_order',
        ),
    ]
