# Generated by Django 3.1.3 on 2021-01-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_table_tablecount_tableview'),
        ('order', '0003_remove_order_mini_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razor_pay_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.table'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancelminiorder',
            name='cancel_mini_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.DeleteModel(
            name='MiniOrder',
        ),
    ]
