# Generated by Django 3.1.3 on 2021-01-12 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20210112_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_requested', models.BooleanField(default=True)),
                ('cancel_status', models.CharField(choices=[('Processing Request', 'Processing Request'), ('CANCEL Denied', 'CANCEL Denied'), ('Cancel Granted', 'Cancel Granted')], default='Processing Cancel Request', max_length=50)),
                ('cancel_granted', models.BooleanField(default=False)),
                ('cancel_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancel_reason', models.CharField(blank=True, choices=[('Not Needed', 'Not Needed'), ('Ordered Wrong Dishes', 'Ordered Wrong Dishes'), ('Receiving To Late', 'Receiving To Late'), ('Other', 'Other')], max_length=50, null=True)),
                ('review_description', models.TextField(help_text='Please Describe in detail reason of cancel.')),
            ],
            options={
                'ordering': ['cancel_date'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('CANCELED', 'CANCELED')], default='Processing', max_length=50),
        ),
        migrations.DeleteModel(
            name='CancelMiniOrder',
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
