# Generated by Django 3.1.3 on 2021-01-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210112_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
