# Generated by Django 3.1.3 on 2021-01-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210112_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(blank=True, to='order.Cart'),
        ),
    ]
