# Generated by Django 3.1.3 on 2021-01-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210112_1905'),
        ('order', '0007_auto_20210112_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.booktable'),
        ),
    ]
