# Generated by Django 3.1.3 on 2021-01-16 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_auto_20210116_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taxes',
        ),
        migrations.AlterField(
            model_name='cancelorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.AlterField(
            model_name='cancelorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='couponcustomer',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.coupon'),
        ),
        migrations.AlterField(
            model_name='couponcustomer',
            name='discount_amount',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
