# Generated by Django 3.1.3 on 2021-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210116_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcustomer',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
